### PR TITLE
Provide enum for packet type / direction and fix direction logic

### LINKED ISSUE #12: Provide proper PacketType type / iota
For readability it would be helpful to have an actual enum providing the same named packet type (a.k.a. direction w.r.t. interface) as provided by the linux kernel.

DoD

- [x] Add proper enum with human readable names
- [x] Check if current logic is actually correct (`packetType == 0` for inbound)
- [x] Delete branch (got merged together with #14 without explicit review / approval)

### PR DESCRIPTION
**Pull request by fako1024**
This actually fixes a regression I introduced when implementing `slimcap` (wrong logic for determining if a packet is outbound). In practice this would have little effect (because it would only hit on broadcast / multicast and similar rare packets), but still. Will raise a matching issue on `goProbe` to amend the logic there. 

Closes #12

### CODE REVIEW

File: capture/capture.go [hunk 1]
```diff
@@ -32,8 +32,17 @@ type Stats struct {
 }
 
 // PacketType denotes the packet type (indicating traffic direction)
+// https://github.com/torvalds/linux/blob/master/include/uapi/linux/if_packet.h
 type PacketType = byte
```
Comment (fako1024) [inline capture/capture.go:36]: Note that I deliberately refrained from making this an explicit type in its own right with a `String()` method etc. because it would incur a barrage of explicit type conversions required all over the place that would make the code less readable for close to no practical benefit (no one will care for a string of the packet type, they care for the _direction_ of the packet, which is provided by the new method `IsInbound()` for the packet itself).

File: capture/capture.go [hunk 2]
```diff
@@ -177,3 +186,8 @@ func (p *Packet) IPLayer() IPLayer {
 func (p *Packet) Type() PacketType {
 	return (*p)[0]
 }
+
+// IsInbound denotes if the packet is inbound w.r.t. the interface
+func (p *Packet) IsInbound() bool {
+	return (*p)[0] != PacketOutgoing
```
Comment (fako1024) [inline capture/capture.go:192]: This is where the regression is actually fixed. So far I've been using `.Type() == 0` to indicate an inbound packet, which is not correct. Like the comment above (taken from the kernel sources) indicates: Anything outbound is of type `4`, hence anything `not` of type 4 is inbound.

**Comment by fako1024** [comment]
@els0r FYI: This got merged automatically together with #14 (because I assumed that you'd see this PR before the other one and based this branch off of that one due to dependency requirements). If you have any objections to these changes let me know (I'll keep the branch alive until then and re-open the issue)...

**Comment by els0r** [comment]
> @els0r FYI: This got merged automatically together with #14 (because I assumed that you'd see this PR before the other one and based this branch off of that one due to dependency requirements). If you have any objections to these changes let me know (I'll keep the branch alive until then and re-open the issue)...

Saw this in the review of the other branch. All good with me
