### PR TITLE
[bugfix] Ring buffer block not automatically released without call to nextPacket()

### LINKED ISSUE #33: Ring buffer block not automatically released without call to nextPacket()
https://github.com/els0r/goProbe/issues/88 revealed yet another small bug: As it turns out the current logic in `afring.go` does not release the current ring buffer packet back to the kernel _as soon as the last packet has been consumed_, but instead upon the subsequent call to `nextPacket()`. In practice this probably won't be a problem, but especially when testing we quite often known exactly how many packets have been process and hence don't even try to perform said call to `nextPacket()` just for the sake of releasing the resource. Consequently, any logic that checks e.g. if all blocks have been consumed will fail in such scenarios.
In addition, the E2E test did reveal yet another data race regarding that buffer (my analysis in #24 was not accurate - it just happens very rarely) that needs to be addressed (which in turn requires the aforementioned bug to be fixed).

DoD

- [x] Ensure that blocks are released to the kernel as soon as all packets have been read
- [x] Fix race condition in block status field
- [x] Fix race condition in `Pipe()` / `run()` methods (we must not return from there until all blocks have been released back to the "kernel", i.e. the mock)
- [x] Add better way of assessing if source is closed (using `syscall.Fcntl`)

### PR DESCRIPTION
**Pull request by fako1024**
Provides several small fixes and some improvements for testing via mock source(s). See inline comments for some pointers.

Closes #33

### CODE REVIEW

File: capture/afpacket/afring/afring_mock.go [hunk 1]
```diff
@@ -187,35 +187,18 @@ func (m *MockSource) CanAddPackets() bool {
 // the ring buffer / TPacketHeader block retirement setting for population of the ring buffer
 func (m *MockSource) Pipe(src capture.Source) chan error {
```
Comment (fako1024) [inline capture/afpacket/afring/afring_mock.go:188]: I've simplified the `Pipe()` method significantly, dropping the whole "fake" block expiry simulation. Thing is: This was racy by definition, because it would create yet another goroutine that was accessing individual parts of the mock ring buffer (and not guarded by the memory barrier of the `getBlockStatus()` and `markBlock()` calls. Fixing that would have required an additional memory barrier, which would also have affected the normal, non-mock process (both in terms of complication and performance). Given that the expiry feature was nice to have but in no way important I think opting for simplicity and performance is the best course of action.

File: capture/afpacket/afring/afring_mock.go [hunk 2]
```diff
@@ -306,21 +297,37 @@ func (m *MockSource) run(errChan chan error) {
 }
 
 func (m *MockSource) getBlockStatus(n int) (status uint32) {
-	return *(*uint32)(unsafe.Pointer(&m.ringBuffer.ring[n*m.blockSize+8]))
+	return atomic.LoadUint32((*uint32)(unsafe.Pointer(&m.ringBuffer.ring[n*m.blockSize+8])))
```
Comment (fako1024) [inline capture/afpacket/afring/afring_mock.go:300]: OKOK, turns out _some_ `atomic` magic is needed (for the mock only, but since the overhead is small and `tPacket` has no easy way of knowing if it's a mock or not I've just made the whole block status atomic).

File: capture/afpacket/afring/afring_mock.go [hunk 3]
```diff
@@ -306,21 +297,37 @@ func (m *MockSource) run(errChan chan error) {
...
 }
 
 func (m *MockSource) markBlock(n int, status uint32) {
-	*(*uint32)(unsafe.Pointer(&m.ringBuffer.ring[n*m.blockSize+8])) = status
+	atomic.StoreUint32((*uint32)(unsafe.Pointer(&m.ringBuffer.ring[n*m.blockSize+8])), status)
+}
+
+func (m *MockSource) hasUserlandBlock() bool {
```
Comment (fako1024) [inline capture/afpacket/afring/afring_mock.go:307]: Used in conjunction with `ForceBlockRelease()` to have the mock wait before really closing (a consumer might still be accessing data).

File: capture/afpacket/socket/socket.go [hunk 4]
```diff
@@ -115,6 +115,12 @@ func (sd FileDescriptor) Close() error {
 	return unix.Close(int(sd))
 }
 
+// IsOpen determines if the file descriptor is open / valid
+func (sd FileDescriptor) IsOpen() bool {
```
Comment (fako1024) [inline capture/afpacket/socket/socket.go:119]: This is a much clearer (and atomic) way of checking if the file descriptor is open or not.

File: capture/afpacket/socket/socket_mock.go [hunk 5]
```diff
@@ -44,8 +48,21 @@ func (m *MockFileDescriptor) IncrementPacketCount(delta int) {
 	m.nPacketsProcessed += delta
 }
 
+// LastPoll return the timestamp of the last poll on the FileDescriptor
+func (m *MockFileDescriptor) LastPoll() int64 {
```
Comment (fako1024) [inline capture/afpacket/socket/socket_mock.go:52]: For tests it's helpful to know when the last poll occurred on the mock FD (e.g. to decide if processing is done, which was surprisingly difficult to do atomically :see_no_evil:). Of course doesn't affect the normal FD.

**Review by els0r — APPROVED** [review]
