### PR TITLE
[bugfix] Fix incorrect handling of mock ring buffer wrap around

### LINKED ISSUE #24: Incorrect handling of mock ring buffer wrap-around
In https://github.com/els0r/goProbe/issues/88 several issues emerged when trying to implement an E2E test scenario. After some tracking down it became clear that those were encountered because the E2E test firstly created a test situation where the mock ring buffer actually ran into a wrap-around (all unit / integration tests before operated within a single "run" through the ring buffer, never exhausting its size).

This issue tracks fixes to the current implementation.

### PR DESCRIPTION
**Pull request by fako1024**
@els0r FYI, this should fix the issues mentioned [here](https://github.com/els0r/goProbe/issues/88#issuecomment-1518602902). Luckily it turned out _not_ to be a fundamental race condition, just incorrect handling (and missing tests) for the mock ring buffer wrap-around. The memory barrier in place via the `TPacket` status field seems to mimic the "real" kernel buffer sufficiently without additional synchronization.

Closes #24

### CODE REVIEW

File: capture/afpacket/afring/afring.go [hunk 1]
```diff
@@ -366,12 +366,12 @@ fetch:
 			}
 
 			// Handle rare cases of runaway packets
-			if s.curTPacketHeader.getStatus()&tPacketStatusCopy != 0 {
+			if s.curTPacketHeader.getStatus()&unix.TP_STATUS_COPY != 0 {
 				if s.curTPacketHeader.nPktsLeft != 0 {
 					fmt.Println(s.link.Name, "WUT (after runaway packet)?", s.curTPacketHeader.nPktsLeft)
 				}
-				s.curTPacketHeader.setStatus(tPacketStatusKernel)
-				s.offset = (s.offset + 1) % int(s.tpReq.frameNr)
```
Comment (fako1024) [inline capture/afpacket/afring/afring.go:374]: Unrelated, but saw the mistake by accident. Could have caused quite catastrophic results in case of this (granted, rare) fallback scenario in the wild which would be close to impossible to catch with a mock test).

File: capture/afpacket/afring/afring.go [hunk 2]
```diff
@@ -390,7 +390,7 @@ fetch:
 			if nextPos != 0 {
 				fmt.Println(s.link.Name, "WUT (after resetting)?", s.curTPacketHeader.nPktsLeft, nextPos)
 			}
-			s.curTPacketHeader.setStatus(tPacketStatusKernel)
+			s.curTPacketHeader.setStatus(unix.TP_STATUS_KERNEL)
```
Comment (fako1024) [inline capture/afpacket/afring/afring.go:393]: Unrelated; Decided to use the globals from the `unix` package instead of local re-definitions. They are unlikely to change in the future, but this feels better.

File: capture/afpacket/afring/afring_mock.go [hunk 3]
```diff
@@ -86,8 +86,8 @@ func NewMockSource(iface string, options ...Option) (*MockSource, error) {
 // This can happen prior to calling run or continuously while consuming data, mimicking the
 // function of an actual ring buffer. Consequently, if the ring buffer is full and elements not
 // yet consumed this function may block
-func (m *MockSource) AddPacket(pkt capture.Packet) {
-	m.addPacket(pkt.Payload(), pkt.TotalLen(), pkt.Type(), 0)
+func (m *MockSource) AddPacket(pkt capture.Packet) error {
+	return m.addPacket(pkt.Payload(), pkt.TotalLen(), pkt.Type(), 0)
```
Comment (fako1024) [inline capture/afpacket/afring/afring_mock.go:90]: Unrelated; Added missing error handling.

File: capture/afpacket/afring/afring_mock.go [hunk 4]
```diff
@@ -107,12 +107,19 @@ func (m *MockSource) addPacket(payload []byte, totalLen uint32, pktType, ipLayer
...
-		*(*uint32)(unsafe.Pointer(&m.ringBuffer.ring[thisBlock*m.blockSize])) = 3                       // version
-		*(*uint32)(unsafe.Pointer(&m.ringBuffer.ring[thisBlock*m.blockSize+8])) = unix.TP_STATUS_KERNEL // status
-		*(*uint32)(unsafe.Pointer(&m.ringBuffer.ring[thisBlock*m.blockSize+16])) = tPacketHeaderLen     // offsetToFirstPkt
+		// Ensure that the packet has already been consumed to avoid race conditions (since there is no
+		// feedback from the receiver we can only poll until the packet status is not TP_STATUS_KERNEL)
+		for m.getBlockStatus(thisBlock) != unix.TP_STATUS_KERNEL {
+			time.Sleep(10 * time.Millisecond)
+		}
+
+		m.markBlock(thisBlock, unix.TP_STATUS_CSUMNOTREADY)
```
Comment (fako1024) [inline capture/afpacket/afring/afring_mock.go:118]: This is the actual catch. This memory barrier was in the wrong place before (further down when releasing the current block to the userspace), which cause the (n+1)th to be written _before_ the nth was released. Works fine as long as the buffer doesn't wrap around, but in that case the first block may have already been overwritten before it was consumed by the user. In addition I needed a third status to block here in case the consumption hasn't started yet before the first wrap-around occurs (otherwise the condition would always be true, causing the block to be overwritten before it was even touched).

File: capture/afpacket/afring/afring.go (hunk 2 above)
Comment (els0r) [reply capture/afpacket/afring/afring.go:393]: Makes sense if they are the ones you are using in the underlying code anyhow.

File: capture/afpacket/afring/afring_mock.go [hunk 5]
```diff
@@ -107,12 +107,19 @@ func (m *MockSource) addPacket(payload []byte, totalLen uint32, pktType, ipLayer
...
-		m.curBlockPos = tPacketHeaderLen
 		thisBlock = m.mockBlockCount % m.nBlocks
 
-		*(*uint32)(unsafe.Pointer(&m.ringBuffer.ring[thisBlock*m.blockSize])) = 3                       // version
-		*(*uint32)(unsafe.Pointer(&m.ringBuffer.ring[thisBlock*m.blockSize+8])) = unix.TP_STATUS_KERNEL // status
-		*(*uint32)(unsafe.Pointer(&m.ringBuffer.ring[thisBlock*m.blockSize+16])) = tPacketHeaderLen     // offsetToFirstPkt
+		// Ensure that the packet has already been consumed to avoid race conditions (since there is no
+		// feedback from the receiver we can only poll until the packet status is not TP_STATUS_KERNEL)
+		for m.getBlockStatus(thisBlock) != unix.TP_STATUS_KERNEL {
+			time.Sleep(10 * time.Millisecond)
```
Comment (els0r) [inline capture/afpacket/afring/afring_mock.go:115]: Nitpick: should be a `const` in its own right, e.g. `const receiverFeedbackWaitInterval = 10 * time.Millisecond` or the like.

**Review by els0r — APPROVED** [review]
As far as I can judge: LGTM

File: capture/afpacket/afring/afring_mock.go (hunk 5 above)
Comment (fako1024) [reply capture/afpacket/afring/afring_mock.go]: Fair point, done!
