### PR TITLE
[bugfix] Fix handling of mock snaplen field in pktHdr for packets smaller than snaplen

### LINKED ISSUE #84: Align mock snaplen handling for pktHdr with reality
If actual packets are truncated / smaller than the defined capture snaplen, the `snaplen` value in the TPacket header is set to the length of the packet, not the snaplen (as it currently the case for the mock source). This usually isn't a problem (because it will just allocate more memory than actually required) but may miss issues that would occur on an "real" capture.

### PR DESCRIPTION
**Pull request by fako1024**
Closes #84

### CODE REVIEW

File: capture/afpacket/afring/afring_zerocopy.go [hunk 1]
```diff
@@ -76,7 +76,7 @@ finalize:
 	pos := pktHdr.ppos + uint32(hdr.pktMac)
 
 	// Return the payload / IP layer subslice & heeader parameters
-	return unsafe.Slice(&pktHdr.data[pos], hdr.snaplen),
+	return unsafe.Slice(&pktHdr.data[pos], hdr.snaplen), // #nosec: G103
```
Comment (fako1024) [inline capture/afpacket/afring/afring_zerocopy.go:79]: Drive-by Linter fix...

**Review by els0r — APPROVED** [review]
