### PR TITLE
[bugfix] Fix warning about false remaining packets in ring buffer when piping mock sources

### LINKED ISSUE #28: Mock piping may cause stray packets on ring buffer when wrapping around
When piping packets from one mock source to another it may happen that after completing a full block int the ring buffer there is a warning (from the crude debugging statement to be removed in #6):
```
mock WUT (after resetting)? 0 150
```

This is caused by the forced block finalization which may leave the `nextOffset` value from a previous run through that block untouched, pointing to a next packet that doesn't exist. This doesn't cause catastrophic problems (because the `nextPacket()` call doesn't advance beyond the expected number of packets in said block) but it's an easy fix (issue was discovered when implementing mock E2E tests in https://github.com/els0r/goProbe/issues/88)

### PR DESCRIPTION
**Pull request by fako1024**
Closes #28

### CODE REVIEW

File: capture/afpacket/afring/afring_mock.go [hunk 1]
```diff
@@ -99,7 +99,7 @@ func (m *MockSource) PacketAddCallbackFn(fn func(payload []byte, totalLen uint32
 // function of an actual ring buffer. Consequently, if the ring buffer is full and elements not
 // yet consumed this function may block
 func (m *MockSource) AddPacket(pkt capture.Packet) error {
-	return m.addPacket(pkt.Payload(), pkt.TotalLen(), pkt.Type(), 0)
+	return m.addPacket(pkt.Payload(), pkt.TotalLen(), pkt.Type(), pkt.IPLayerOffset())
```
Comment (fako1024) [inline capture/afpacket/afring/afring_mock.go:102]: This is unrelated, but occurred to me: Now that a `capture.Packet` provides access to its specific IP layer offset we can properly hand it over (caused an issue when piping from mock to mock with different `snaplen`).

File: capture/afpacket/afring/afring_test.go [hunk 2]
```diff
@@ -235,7 +235,7 @@ func TestPipe(t *testing.T) {
 
 	// Setup the original mock source
 	mockSrc, err := NewMockSource("mock",
-		CaptureLength(link.CaptureLengthMinimalIPv4Transport),
+		CaptureLength(link.CaptureLengthMinimalIPv6Transport),
```
Comment (fako1024) [inline capture/afpacket/afring/afring_test.go:238]: Changed this to trigger the IP layer offset issue mentioned in my first comment.

**Review by els0r — APPROVED** [review]
Thanks!
