### PR TITLE
[bugfix] Fix handling of mock snaplen field in pktHdr for packets smaller than snaplen

### LINKED ISSUE #84: Align mock snaplen handling for pktHdr with reality
If actual packets are truncated / smaller than the defined capture snaplen, the `snaplen` value in the TPacket header is set to the length of the packet, not the snaplen (as it currently the case for the mock source). This usually isn't a problem (because it will just allocate more memory than actually required) but may miss issues that would occur on an "real" capture.

### PR DESCRIPTION
**Pull request by fako1024**
Second attempt - took the wrong default value and found a few other unwanted side-effect / inconsistencies that only occur for the edge case of payloads smaller than the snaplen _and_ situations where it's important that the data length isn't spare.

Closes #84

### CODE REVIEW

File: capture/afpacket/afring/afring.go [hunk 1]
```diff
@@ -121,7 +121,7 @@ func NewSourceFromLink(link *link.Link, options ...Option) (*Source, error) {
 // NextIPPacket() methods (the latter two by calling .Payload() / .IPLayer() on the created buffer). It ensures
 // that a valid packet of appropriate structure / length is created
 func (s *Source) NewPacket() capture.Packet {
-	p := make(capture.Packet, 6+s.snapLen)
+	p := make(capture.Packet, capture.PacketHdrOffset+s.snapLen)
```
Comment (fako1024) [inline capture/afpacket/afring/afring.go:124]: Drive-by code cleanup (uses newly introduced `const`).

File: capture/afpacket/afring/afring_mock.go [hunk 2]
```diff
@@ -141,7 +141,7 @@ func (m *MockSource) addPacket(payload []byte, totalLen uint32, pktType, ipLayer
 	block := m.ringBuffer.ring[thisBlock*m.blockSize : thisBlock*m.blockSize+m.blockSize]
 
 	*(*tPacketHeaderV3Mock)(unsafe.Pointer(&block[m.curBlockPos+12])) = tPacketHeaderV3Mock{
-		snaplen: min(uint32(m.snapLen), totalLen), // The snaplen is set to the totalLen if a packet is shorter
+		snaplen: min(uint32(m.snapLen), uint32(len(payload))), // The snaplen is set to the totalLen if a packet is shorter
```
Comment (fako1024) [inline capture/afpacket/afring/afring_mock.go:144]: This was incorrect. The `totalLen` of course is the wrong value to take here, what matters is the actual length of the captured fraction of the packet.

**Review by els0r — APPROVED** [review]
